# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 06:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseLTIObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_attributes', jsonfield.fields.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('properties_domain', models.CharField(default=b'testing_here', max_length=255)),
                ('properties_privacy_level', models.CharField(choices=[('public', 'public'), ('email', 'email'), ('name', 'name'), ('anonymous', 'anonymous')], max_length=255)),
                ('properties_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTIConsumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='OptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('course_navigation', 'Course Navigation'), ('account_navigation', 'Account Navigation'), ('user_navigation', 'User Navigation'), ('editor_button', 'Richtext Editor Button'), ('labels', 'Translations'), ('resource_selection', 'Resource Selection')], max_length=50)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='dj_pylti.Configuration')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dj_pylti.OptionList')),
            ],
        ),
        migrations.CreateModel(
            name='OptionProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('choices', jsonfield.fields.JSONField(blank=True, default=[], null=True)),
                ('default', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTIContext',
            fields=[
                ('baseltiobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_pylti.BaseLTIObject')),
                ('context_id', models.CharField(max_length=255)),
                ('context_label', models.CharField(max_length=255)),
            ],
            bases=('dj_pylti.baseltiobject',),
        ),
        migrations.CreateModel(
            name='LTIResource',
            fields=[
                ('baseltiobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_pylti.BaseLTIObject')),
                ('resource_link_id', models.CharField(max_length=255)),
                ('resource_link_title', models.CharField(max_length=255)),
            ],
            bases=('dj_pylti.baseltiobject',),
        ),
        migrations.CreateModel(
            name='LTIUserProfile',
            fields=[
                ('baseltiobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dj_pylti.BaseLTIObject')),
                ('lti_user_id', models.CharField(max_length=255, unique=True)),
                ('lis_person_contact_email_primary', models.CharField(max_length=255)),
                ('lis_person_name_family', models.CharField(max_length=255)),
                ('lis_person_name_full', models.CharField(max_length=255)),
                ('lis_person_name_given', models.CharField(max_length=255)),
                ('user', models.ForeignKey(db_column='user_id_int', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('dj_pylti.baseltiobject',),
        ),
        migrations.AddField(
            model_name='optionproperty',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj_pylti.PropertyName'),
        ),
        migrations.AddField(
            model_name='optionproperty',
            name='option_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='dj_pylti.OptionList'),
        ),
    ]
